# Generated by Django 5.2.5 on 2025-08-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='generic_name',
        ),
    ]
