# Generated by Django 5.2.5 on 2025-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='response_time',
            field=models.CharField(choices=[('instant', 'Instantly'), ('3-5', 'Within 3 to 5 hours'), ('longer', 'A little longer')], default='instant', max_length=10),
        ),
    ]
