# Generated by Django 5.2.5 on 2025-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supplier_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='response_time',
            field=models.CharField(choices=[('instantly', 'Instantly'), ('3-5', 'Within 3 to 5 hours'), ('longer', 'A little longer')], default='instantly', max_length=10),
        ),
    ]
