# Generated by Django 5.2.5 on 2025-08-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supplier_response_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('illegal_fraudulent', 'This is illegal/fraudulent'), ('spam', 'This product is spam'), ('wrong_price', 'The price is wrong'), ('wrong_category', 'Wrong category'), ('prepayment', 'Seller asked for prepayment'), ('sold', 'It is sold'), ('unreachable_user', 'User is unreachable'), ('counterfeit', 'This product is counterfeit/fake'), ('offensive_content', 'Contains offensive or inappropriate content'), ('misleading', 'Misleading or false information'), ('duplicate', 'Duplicate listing'), ('expired', 'Product expired or outdated'), ('prohibited_item', 'Prohibited item for sale'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Optional, provide details if reason is "Other"', null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='core.product')),
            ],
        ),
    ]
