# Generated by Django 5.2.5 on 2025-08-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reportabuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
