# Generated by Django 5.2.5 on 2025-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='response_time',
            field=models.CharField(choices=[('instantly', 'Instantly'), ('3-5', 'Within 3 to 5 Minutes'), ('longer', 'A little longer')], default='instantly', max_length=10),
        ),
    ]
