# Generated by Django 5.2.5 on 2025-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_supplier_email_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
