# Generated by Django 5.2.5 on 2025-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_discount_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
