# Generated by Django 5.2.5 on 2025-08-14 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_bulk_discount_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dosage_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage', to='core.dosageform'),
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('sell_person', models.ImageField(upload_to='provider/sell_persons/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_supplier', to='core.supplier')),
            ],
        ),
    ]
