# Generated by Django 5.2.5 on 2025-08-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_dosage_form_userproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='core.product'),
        ),
    ]
