# Generated by Django 5.2.5 on 2025-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_userproducts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproducts',
            old_name='Product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bulk_discount_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_delivery',
        ),
        migrations.AddField(
            model_name='userproducts',
            name='bulk_discount_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproducts',
            name='offer_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
