# Generated by Django 5.2.5 on 2025-08-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_product_userproducts_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='product',
        ),
    ]
