# Generated by Django 5.2.5 on 2025-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_userproducts_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='sell_person',
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
