# Generated by Django 5.2.5 on 2025-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_userproducts_sell_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
