# Generated by Django 5.2.5 on 2025-08-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_userproducts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_supplier', to='core.supplier'),
        ),
    ]
