# Generated by Django 5.2.5 on 2025-08-16 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_months',
        ),
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
