# Generated by Django 5.2.5 on 2025-08-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_product_shelf_life_months_product_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
    ]
