# Generated by Django 5.2.5 on 2025-08-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_product_pack_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_used', models.IntegerField(default=1)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('posted', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_posts', to='core.supplier')),
            ],
        ),
    ]
