# Generated by Django 5.2.5 on 2025-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('wholesaler', 'wholesaler'), ('buyer', 'buyer'), ('partnership', 'partnership'), ('support', 'support'), ('other', 'other')])),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
