# Generated by Django 5.2.5 on 2025-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ai_generated', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('facebook_page', 'Facebook Page'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('telegram_group', 'Telegram Group'), ('telegram_channel', 'Telegram Channel')], max_length=50)),
                ('posted', models.BooleanField(default=False)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('wholesaler', 'wholesaler'), ('buyer', 'buyer'), ('partnership', 'partnership'), ('support', 'support'), ('other', 'other')], max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_delivery_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_pharmacy_name',
            field=models.CharField(max_length=200),
        ),
    ]
