# Generated by Django 5.2.5 on 2025-09-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0006_rename_product_medicaldevice'),
        ('core', '0033_post_alter_contactus_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='medical_device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Medical_device.medicaldevice'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.product'),
        ),
    ]
