# Generated by Django 5.2.5 on 2025-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0008_alter_medicaldevice_description'),
        ('core', '0035_remove_orderitem_medical_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='devices',
            field=models.ManyToManyField(blank=True, to='Medical_device.medicaldevice'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
