# Generated by Django 5.2.5 on 2025-09-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_city_supplier_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosageform',
            options={'ordering': ['id']},
        ),
    ]
