# Generated by Django 5.2.5 on 2025-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0002_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
