# Generated by Django 5.2.5 on 2025-09-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0004_product_warranty'),
        ('core', '0033_post_alter_contactus_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.supplier'),
            preserve_default=False,
        ),
    ]
