# Generated by Django 5.2.5 on 2025-09-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0005_product_supplier'),
        ('core', '0033_post_alter_contactus_subject_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='MedicalDevice',
        ),
    ]
