# Generated by Django 5.2.5 on 2025-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0007_impressionaggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldevice',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
