# Generated by Django 5.2.5 on 2025-09-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medical_device', '0008_alter_medicaldevice_description'),
        ('core', '0039_alter_dosageform_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medical_device.category')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industries', models.ManyToManyField(blank=True, to='setting.industry')),
                ('regions', models.ManyToManyField(blank=True, to='core.city')),
                ('specialized_equipment', models.ManyToManyField(blank=True, to='setting.equipmenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
    ]
