# Generated by Django 5.2.5 on 2025-09-20 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0008_alter_medicaldevice_description'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='regions',
            new_name='cities',
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Medical_device.category'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
