# Generated by Django 5.2.5 on 2025-09-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_rename_regions_supplierprofile_cities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='cities',
            new_name='regions',
        ),
        migrations.RemoveField(
            model_name='supplierprofile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='supplierprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierprofile',
            name='updated_at',
        ),
    ]
