# Generated by Django 5.2.5 on 2025-09-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_rename_cities_supplierprofile_regions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='regions',
            new_name='cities',
        ),
    ]
