# Generated by Django 5.2.5 on 2025-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_device', '0008_alter_medicaldevice_description'),
        ('setting', '0004_rename_regions_supplierprofile_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='specialized_equipment',
            field=models.ManyToManyField(blank=True, to='Medical_device.category'),
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
    ]
