# Generated by Django 5.2.5 on 2025-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_dosageform_options'),
        ('setting', '0007_quoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='name',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='core.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
