# Generated by Django 5.2.5 on 2025-09-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_remove_quoterequest_contact_remove_quoterequest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quote_images/')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='setting.quoterequest')),
            ],
        ),
    ]
