# Generated by Django 5.2.5 on 2025-09-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_dosageform_options'),
        ('setting', '0009_quoteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.supplier'),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.supplier'),
        ),
    ]
